name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v2

      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Manual activation file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
